name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g yarn
      - run: npm install -g makeshift && makeshift -s @bloomberg
      - run: yarn
      - run: yarn bootstrap
      - run: yarn build
      - run: npm publish
        working-directory: packages/record-tuple-polyfill
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
